### ISSUE TITLE
Install reportportal v5 chart dependencies automatically

### ISSUE THREAD

**Issue by epam-valerii** [reportportal/kubernetes#110]
I did not understand why do you suggest installing chart dependencies manually in readme of reportportal v5.

So I prepared values.yaml file which allows to deploy reportportal in three commands. (Name of release should be `reportportal` in this case)
```bash
helm dependencies build ./reportportal/v5
helm package ./reportportal/v5
helm -n rptest install reportportal ./reportportal-5.tgz -f ./values.yaml
```

values.yaml:
```yaml
rabbitmq-ha:
  rabbitmqUsername: rabbitmq
  rabbitmqPassword: rabbitmqpass
  replicaCount: 1
  persistentVolume:
    enabled: true
rabbitmq:
  SecretName: reportportal-rabbitmq-ha
  installdep:
    enable: true
  endpoint:
    address: reportportal-rabbitmq-ha
    user: rabbitmq
    apiuser: rabbitmq

postgresql:
  initdbScripts:
    #from /reportportal/v5/postgresql/values.yaml
    init_postgres.sh: |
      #!/bin/sh
      /opt/bitnami/postgresql/bin/psql -U postgres -d ${POSTGRES_DB} -c 'CREATE EXTENSION IF NOT EXISTS ltree; CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS pg_trgm;'
  postgresqlDatabase: reportportal
  postgresqlUsername: postgres
  postgresqlPassword: reportportalpostgres

  SecretName: reportportal-postgresql
  installdep:
    enable: true
  endpoint:
    address: reportportal-postgresql
    user: postgres
    dbName: reportportal

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  installdep:
    enable: true

minio:
  secretName: reportportal-minio
  installdep:
    enable: true
  endpoint: http://reportportal-minio:9000
```

Additionally, you could add `nginx-ingress` to `requirements.yaml` to make instalation even more simper
```yaml
  - name: nginx-ingress
    version: 1.34.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.installdep.enable
```
