### ISSUE TITLE
reportportal under path

### ISSUE THREAD

**Issue by artyom-gatalsky** [reportportal/kubernetes#116]
Hello, I need to setup report portal under path, e.g
https://example.com/reportportal

What changes should be done in the ingress template? I've managed to reach login page and nothing more.
My ingress config:
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 128m
      nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    generation: 5
    labels:
      app: reportportal
      chart: reportportal-5
      heritage: Helm
      release: reportportal
    name: reportportal-gateway-ingress
    namespace: reportportal
  spec:
    rules:
    - host: example.com
      http:
        paths:
        - backend:
            serviceName: reportportal-index
            servicePort: headless
          path: /reportportal/()?(.*)
        - backend:
            serviceName: reportportal-ui
            servicePort: headless
          path: /reportportal/(ui)/?(.*)
        - backend:
            serviceName: reportportal-uat
            servicePort: headless
          path: /reportportal/(uat)/?(.*)
        - backend:
            serviceName: reportportal-api
            servicePort: headless
          path: /reportportal/(api)/?(.*)
    tls:
    - hosts:
      - example.com
      secretName: example-tls
```
