### ISSUE TITLE
Unable to install or upgrade chart on Kubernetes 1.16+

### ISSUE THREAD

**Issue by vutny** [reportportal/kubernetes#143]
Hello.

While enabling MinIO as the dependency, the chart can be neither installed nor upgraded on K8s 1.16 clusters and newer.
Helm outputs following error:
```
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: unable to recognize "":
no matches for kind "Deployment" in version "apps/v1beta2"
```

The values are set as:
```
minio:
  enabled: true
  installdep:
    enable: true
  endpoint: http://reportportal-minio.reportportal.svc.cluster.local:9000
  region:
  secretName: reportportal-minio
  accesskey:
  secretkey:
```
