### ISSUE TITLE
Error: failed pre-install: warning: Hook pre-install reportportal/templates/migrations-job.yaml failed: Job.batch "reportportal-migrations" is invalid

### ISSUE THREAD

**Issue by patsevanton** [reportportal/kubernetes#177]
Hello! Thanks for reportportal
I try install reportportal into kubernetes by helm

**cd reportportal/
helm dep update**
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://helm.elastic.co" chart repository
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading postgresql from repo https://charts.helm.sh/stable
Downloading rabbitmq from repo https://charts.bitnami.com/bitnami
Downloading elasticsearch from repo https://helm.elastic.co
Downloading minio from repo https://charts.helm.sh/stable
Deleting outdated charts

**cd ..
helm install reportportal ./reportportal/**
Error: failed pre-install: warning: Hook pre-install reportportal/templates/migrations-job.yaml failed: Job.batch "reportportal-migrations" is invalid: spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by patsevanton** [comment]
Need set SecretName and password for rabbitmq and postgresql

```
rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: <rabbitmq_chart_name>.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq

postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    cloudservice: false
    address: <postgresql_chart_name>.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password: 
```
