### ISSUE TITLE
CreateContainerConfigError Error: secret "secretpostgresql" not found

### ISSUE THREAD

**Issue by patsevanton** [reportportal/kubernetes#178]
Hello! Thanks for reportportal
I try install reportportal into kubernetes by helm
I use **default namespace**

**git clone https://github.com/reportportal/kubernetes.git
cd kubernetes/reportportal/
helm dep update**
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://helm.elastic.co" chart repository
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading postgresql from repo https://charts.helm.sh/stable
Downloading rabbitmq from repo https://charts.bitnami.com/bitnami
Downloading elasticsearch from repo https://helm.elastic.co
Downloading minio from repo https://charts.helm.sh/stable
Deleting outdated charts

Set SecretName and password for rabbitmq and postgresql

```
rabbitmq:
  SecretName: "xxxxxxx"
  installdep:
    enable: false
  endpoint:
    address: <rabbitmq_chart_name>.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq

postgresql:
  SecretName: "zzzzzzzz"
  installdep:
    enable: false
  endpoint:
    cloudservice: false
    address: <postgresql_chart_name>.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password: yyyyyyy
```

**cd ..
helm install reportportal ./reportportal/**

Status of reportportal-migrations
```
kubectl get all 
NAME                                READY   STATUS                       RESTARTS   AGE
pod/reportportal-migrations-fmnml   0/1     CreateContainerConfigError   0          3m48s

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   4d

NAME                                COMPLETIONS   DURATION   AGE
job.batch/reportportal-migrations   0/1           3m49s      3m49s
```

**kubectl describe pod/reportportal-migrations-fmnml**
```
Name:         reportportal-migrations-fmnml
Namespace:    default
Priority:     0
Node:         ecse00500bf2/10.66.220.56
Start Time:   Mon, 05 Jul 2021 10:50:56 +0600
Labels:       component=reportportal-migrations
              controller-uid=c6a5fcfc-1bf6-4ebd-93c6-fdd8f33ab186
              job-name=reportportal-migrations
Annotations:  <none>
Status:       Pending
IP:           10.1.99.32
IPs:
  IP:           10.1.99.32
Controlled By:  Job/reportportal-migrations
Containers:
  migrations:
    Container ID:   
    Image:          reportportal/migrations:5.4.0
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      POSTGRES_SERVER:    <postgresql_chart_name>-postgresql.default.svc.cluster.local
      POSTGRES_DB:        reportportal
      POSTGRES_PORT:      5432
      POSTGRES_USER:      rpuser
      POSTGRES_PASSWORD:  <set to the key 'postgresql-password' in secret 'secretpostgresql'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gzkt2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-gzkt2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gzkt2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m47s                   default-scheduler  Successfully assigned default/reportportal-migrations-fmnml to ecse00500bf2
  Normal   Pulled     2m30s (x12 over 4m45s)  kubelet            Container image "reportportal/migrations:5.4.0" already present on machine
  Warning  Failed     2m16s (x13 over 4m45s)  kubelet            Error: secret "secretpostgresql" not found
```
