### ISSUE TITLE
kubelet            Error: secret "<db_chart_name>-postgresql" not found

### ISSUE THREAD

**Issue by patsevanton** [reportportal/kubernetes#180]
Hello! I try install reportportal by instruction

```
helm repo add stable https://charts.helm.sh/stable
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add elastic https://helm.elastic.co
helm repo update
```

Install dependencies
```
helm install elasticsearch elastic/elasticsearch --set replicas=1 -f value-elastic.yaml --version 7.6.1

helm install minio --set accessKey=accesskey,secretKey=secretkey stable/minio

helm install postgresql --set postgresqlUsername=rpuser,postgresqlPassword=password,postgresqlDatabase=reportportal,postgresqlPostgresPassword=password -f ./reportportal/postgresql/values.yaml  bitnami/postgresql --version 8.6.2

helm install rabbitmq --set auth.username=rabbitmq,auth.password=password,replicaCount=1 bitnami/rabbitmq --version 7.5.6
```

Install reportportal
```
helm install reportportal --set postgresql.SecretName=postgresql-postgresql,rabbitmq.SecretName=rabbitmq ./reportportal
```

Get error:
```
kubectl describe pod/reportportal-migrations-vv2lj 
Name:         reportportal-migrations-vv2lj
Namespace:    default
Priority:     0
Node:         ecse00500bfa/10.66.217.150
Start Time:   Tue, 06 Jul 2021 10:08:37 +0600
Labels:       component=reportportal-migrations
              controller-uid=d9ad21a2-a983-439d-87ec-b389deef6cf9
              job-name=reportportal-migrations
Annotations:  <none>
Status:       Pending
IP:           10.1.95.18
IPs:
  IP:           10.1.95.18
Controlled By:  Job/reportportal-migrations
Containers:
  migrations:
    Container ID:   
    Image:          reportportal/migrations:5.4.0
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      POSTGRES_SERVER:    postgresql.default.svc.cluster.local
      POSTGRES_DB:        reportportal
      POSTGRES_PORT:      5432
      POSTGRES_USER:      rpuser
      POSTGRES_PASSWORD:  <set to the key 'postgresql-password' in secret 'postgresql-postgresql'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wtj6x (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-wtj6x:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wtj6x
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m41s                  default-scheduler  Successfully assigned default/reportportal-migrations-vv2lj to ecse00500bfa
  Warning  Failed     3m56s (x3 over 4m39s)  kubelet            Failed to pull image "reportportal/migrations:5.4.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/reportportal/migrations:5.4.0": failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/reportportal/migrations/manifests/sha256:36cdf01cd8412b72272faf6ebce5ad831b754f96403e6c05f34c69f05785f281: 429 Too Many Requests
  Warning  Failed     3m56s (x3 over 4m39s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3m21s (x5 over 4m38s)  kubelet            Back-off pulling image "reportportal/migrations:5.4.0"
  Warning  Failed     3m21s (x5 over 4m38s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    3m8s (x4 over 4m40s)   kubelet            Pulling image "reportportal/migrations:5.4.0"
  Normal   Pulled     3m                     kubelet            Successfully pulled image "reportportal/migrations:5.4.0"
  Warning  Failed     2m49s (x2 over 3m)     kubelet            Error: secret "postgresql-postgresql" not found
  Normal   Pulled     2m36s (x2 over 2m49s)  kubelet            Container image "reportportal/migrations:5.4.0" already present on machine
```

File value-elastic.yaml with content:
```
## String to partially override reportportal.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override reportportal.fullname template
##
# fullnameOverride:

serviceindex:
  name: index
  repository: reportportal/service-index
  tag: 5.0.10
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  podAnnotations: {}
  securityContext: {}

uat:
  repository: reportportal/service-authorization
  name: uat
  tag: 5.4.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  podAnnotations: {}
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
  securityContext: {}
  serviceAccountName: ""

serviceui:
  repository: reportportal/service-ui
  tag: v5.4.0
  name: ui
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

serviceapi:
  repository: reportportal/service-api
  tag: 5.4.0
  name: api
  pullPolicy: IfNotPresent
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 20
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:MinRAMPercentage=60.0 -XX:InitiatingHeapOccupancyPercent=70 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  queues:
    totalNumber: 
    perPodNumber: 
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

servicejobs:
  repository: reportportal/service-jobs
  tag: 5.4.0
  name: jobs
  pullPolicy: IfNotPresent
  clean:
    chunksize: 1000
    cron:
      attachment: 0 0 */24 * * *
      log: 0 0 */24 * * *
      launch: 0 0 */24 * * *
      storage: 0 0 */24 * * *
      storageproject: 0 */5 * * * *
  resources:
    requests:
      cpu: 100m
      memory: 248Mi
    limits:
      cpu: 100m
      memory: 372Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

migrations:
  repository: reportportal/migrations
  tag: 5.4.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""
  metadataAnnotations:
    enabled: true
    hooks:
      "helm.sh/hook": "pre-install,pre-upgrade"
      "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"

serviceanalyzer:
  repository: reportportal/service-auto-analyzer
  tag: 5.4.0
  name: analyzer
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

serviceanalyzertrain:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

rabbitmq:
  SecretName: "rabbitmq"
  installdep:
    enable: false
  endpoint:
    cloudservice: false
    address: rabbitmq.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password: password

postgresql:
  SecretName: "postgresql"
  installdep:
    enable: false
  endpoint:
    cloudservice: false
    address: postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password: password

elasticsearch:
  installdep:
    enable: false
  endpoint: http://elasticsearch-master:9200

minio:
  secretName: "minio"
  enabled: true
  installdep:
    enable: false
  endpoint: http://minio.default.svc.cluster.local:9000
  endpointshort: minio.default.svc.cluster.local:9000
  region:
  accesskey: accesskey
  secretkey: secretkey

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true


# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
      create: true
      name: reportportal

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"
```
