### ISSUE TITLE
Deploy the ReportPortal Helm Chart If you use PostgreSQL Helm chart incorrect in readme

### ISSUE THREAD

**Issue by patsevanton** [reportportal/kubernetes#193]
Hello! I try install reportportal by instruction https://github.com/reportportal/kubernetes/tree/master/reportportal

**kubectl get nodes** 
```
NAME                        STATUS   ROLES    AGE   VERSION
cl1v785b1pfsu02d7o01-eriz   Ready    <none>   48m   v1.18.18
cl1v785b1pfsu02d7o01-ykyk   Ready    <none>   48m   v1.18.18
cl1v785b1pfsu02d7o01-yxiz   Ready    <none>   48m   v1.18.18
```

**Add repo**
```
helm repo add stable https://charts.helm.sh/stable
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add elastic https://helm.elastic.co
```

**kubectl label nodes**
```
kubectl label nodes cl1v785b1pfsu02d7o01-eriz service=api
kyk service=rabbitmq
kubectl label nodes cl1v785b1pfsu02d7o01-yxiz service=db
node/cl1v785b1pfsu02d7o01-eriz labeled
kubectl label nodes cl1v785b1pfsu02d7o01-ykyk service=rabbitmq
node/cl1v785b1pfsu02d7o01-ykyk labeled
```

**helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update**
```
"ingress-nginx" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "elastic" chart repository
Update Complete. ⎈Happy Helming!⎈
```

**helm install nginx-ingress ingress-nginx/ingress-nginx**
```
NAME: nginx-ingress
LAST DEPLOYED: Fri Aug 20 04:54:32 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace default get services -o wide -w nginx-ingress-ingress-nginx-controller'

An example Ingress that makes use of the controller:

  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: example
    namespace: foo
  spec:
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                serviceName: exampleService
                servicePort: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.example.com
          secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls
```

**helm install elasticsearch ./reportportal/charts/elasticsearch-7.6.1.tgz**
```
NAME: elasticsearch
LAST DEPLOYED: Fri Aug 20 04:58:26 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Watch all cluster members come up.
  $ kubectl get pods --namespace=default -l app=elasticsearch-master -w
2. Test cluster health using Helm test.
  $ helm test elasticsearch
```

**helm dependency build ./reportportal/**
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading postgresql from repo https://charts.helm.sh/stable
Downloading rabbitmq from repo https://charts.bitnami.com/bitnami
Downloading elasticsearch from repo https://helm.elastic.co
Downloading minio from repo https://charts.helm.sh/stable
Deleting outdated charts
```

**helm install rabbitmq --set auth.username=rabbitmq,auth.password=password,replicaCount=1 ./reportportal/charts/rabbitmq-7.5.6.tgz**
```
NAME: rabbitmq
LAST DEPLOYED: Fri Aug 20 04:59:28 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Credentials:

    echo "Username      : rabbitmq"
    echo "Password      : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
    echo "ErLang Cookie : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"

RabbitMQ can be accessed within the cluster on port  at rabbitmq.default.svc.

To access for outside the cluster, perform the following steps:

To Access the RabbitMQ AMQP port:

    echo "URL : amqp://127.0.0.1:5672/"
    kubectl port-forward --namespace default svc/rabbitmq 5672:5672

To Access the RabbitMQ Management interface:

    echo "URL : http://127.0.0.1:15672/"
    kubectl port-forward --namespace default svc/rabbitmq 15672:15672
```

**kubectl exec -it rabbitmq-0 -- rabbitmqctl set_vm_memory_high_watermark 0.8**
```
Setting memory threshold on rabbit@rabbitmq-0.rabbitmq-headless.default.svc.cluster.local to 0.8 ...
```

**helm install postgresql --set postgresqlUsername=rpuser,postgresqlPassword=password,postgresqlDatabase=reportportal,postgresqlPostgresPassword=password -f ./reportportal/postgresql/values.yaml ./reportportal/charts/postgresql-8.6.2.tgz**
```
NAME: postgresql
LAST DEPLOYED: Fri Aug 20 05:03:16 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS name from within your cluster:

    postgresql.default.svc.cluster.local - Read/Write connection

To get the password for "postgres" run:

    export POSTGRES_ADMIN_PASSWORD=$(kubectl get secret --namespace default postgresql -o jsonpath="{.data.postgresql-postgres-password}" | base64 --decode)

To get the password for "rpuser" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.7.0-debian-10-r9 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host postgresql -U rpuser -d reportportal -p 5432



To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U rpuser -d reportportal -p 5432
```

**helm install minio --set accessKey=accesskey,secretKey=secretkey,persistence.size=40Gi stable/minio**
```
WARNING: This chart is deprecated

NAME: minio
LAST DEPLOYED: Fri Aug 20 05:05:35 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Minio can be accessed via port 9000 on the following DNS name from within your cluster:
minio.default.svc.cluster.local

To access Minio from localhost, run the below commands:

  1. export POD_NAME=$(kubectl get pods --namespace default -l "release=minio" -o jsonpath="{.items[0].metadata.name}")

  2. kubectl port-forward $POD_NAME 9000 --namespace default

Read more about port forwarding here: http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/

You can now access Minio server on http://localhost:9000. Follow the below steps to connect to Minio server with mc client:

  1. Download the Minio mc client - https://docs.minio.io/docs/minio-client-quickstart-guide

  2. mc config host add minio-local http://localhost:9000 accesskey secretkey S3v4

  3. mc ls minio-local

Alternately, you can use your browser or the Minio SDK to access the server - https://docs.minio.io/categories/17
```

**helm package ./reportportal/**
```
Successfully packaged chart and saved it to: /home/apatsev/reportportal/reportportal-5.5.0.tgz
```

**helm install reportportal --set postgresql.SecretName=postgresql-postgresql,rabbitmq.SecretName=rabbitmq ./reportportal-5.5.0.tgz** 
```
Error: failed pre-install: timed out waiting for the condition
```

Get error when install 
```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  117s                default-scheduler  Successfully assigned default/reportportal-migrations-pl2cw to cl1v785b1pfsu02d7o01-yxiz
  Normal   Pulling    116s                kubelet            Pulling image "reportportal/migrations:5.5.0"
  Normal   Pulled     112s                kubelet            Successfully pulled image "reportportal/migrations:5.5.0"
  Warning  Failed     9s (x10 over 112s)  kubelet            Error: secret "postgresql-postgresql" not found
  Normal   Pulled     9s (x9 over 111s)   kubelet            Container image "reportportal/migrations:5.5.0" already present on machine
```

**Comment by patsevanton** [comment]
Everything exactly according to the instructions

**Comment by patsevanton** [comment]
In https://github.com/reportportal/kubernetes/tree/master/reportportal#6-postgresql-installation - dont have instructions for create secret

**Comment by patsevanton** [comment]
If run
**helm install reportportal --set postgresql.SecretName=postgresql,rabbitmq.SecretName=rabbitmq ./reportportal-5.5.0.tgz**

I get error
**kubectl logs pod/reportportal-migrations-b7nsm**
```
wait-for-it.sh: waiting 15 seconds for postgresql-postgresql.default.svc.cluster.local:5432
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
nc: bad address 'postgresql-postgresql.default.svc.cluster.local'
wait-for-it.sh: timeout occurred after waiting 15 seconds for postgresql-postgresql.default.svc.cluster.local:5432
error: dial tcp: lookup postgresql-postgresql.default.svc.cluster.local on 10.96.128.2:53: no such host
```

**Comment by patsevanton** [comment]
**helm install reportportal --set postgresql.SecretName=postgresql,rabbitmq.SecretName=rabbitmq ./reportportal-5.5.0.tgz**

**kubectl get pod -A**
```
NAMESPACE     NAME                                                    READY   STATUS    RESTARTS   AGE
default       elasticsearch-master-0                                  1/1     Running   0          43m
default       elasticsearch-master-1                                  1/1     Running   0          43m
default       elasticsearch-master-2                                  1/1     Running   0          43m
default       minio-66678bbbf9-7t2cc                                  1/1     Running   0          40m
default       nginx-ingress-ingress-nginx-controller-c65d8cf9-6mk8t   1/1     Running   0          44m
default       postgresql-postgresql-0                                 1/1     Running   0          40m
default       rabbitmq-0                                              1/1     Running   0          42m
default       reportportal-analyzer-0                                 1/1     Running   0          5m32s
default       reportportal-analyzer-train-0                           1/1     Running   0          5m32s
default       reportportal-api-5c6d47d77-glbpt                        1/1     Running   0          5m32s
default       reportportal-index-d7fcdcf97-z8b5b                      1/1     Running   0          5m32s
default       reportportal-jobs-74c4ffb6dc-sx6w8                      1/1     Running   0          5m31s
default       reportportal-metrics-gatherer-7cc97b8fd9-rcddn          1/1     Running   0          5m32s
default       reportportal-uat-5bc7f785d5-r7r5f                       1/1     Running   0          5m32s
default       reportportal-ui-69b55b9b44-fg4d7                        1/1     Running   0          5m32s
```

**cat reportportal/values.yaml** 
```
## String to partially override reportportal.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override reportportal.fullname template
##
# fullnameOverride:

serviceindex:
  name: index
  repository: reportportal/service-index
  tag: 5.0.10
  pullPolicy: Always
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  podAnnotations: {}
  securityContext: {}

uat:
  repository: reportportal/service-authorization
  name: uat
  tag: 5.5.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  podAnnotations: {}
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
  securityContext: {}
  serviceAccountName: ""

serviceui:
  repository: reportportal/service-ui
  tag: 5.5.0
  name: ui
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

serviceapi:
  repository: reportportal/service-api
  tag: 5.5.0
  name: api
  pullPolicy: Always
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 20
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:MinRAMPercentage=60.0 -XX:InitiatingHeapOccupancyPercent=70 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  queues:
    totalNumber:
    perPodNumber:
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

servicejobs:
  repository: reportportal/service-jobs
  tag: 5.5.0
  name: jobs
  pullPolicy: Always
  clean:
    chunksize: 1000
    cron:
      attachment: 0 0 */24 * * *
      log: 0 0 */24 * * *
      launch: 0 0 */24 * * *
      storage: 0 0 */24 * * *
      storageproject: 0 */5 * * * *
  resources:
    requests:
      cpu: 100m
      memory: 248Mi
    limits:
      cpu: 100m
      memory: 372Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

migrations:
  repository: reportportal/migrations
  tag: 5.5.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""
  metadataAnnotations:
    enabled: true
    hooks:
      "helm.sh/hook": "pre-install,pre-upgrade"
      "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"

serviceanalyzer:
  repository: reportportal/service-auto-analyzer
  tag: 5.5.0
  name: analyzer
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

serviceanalyzertrain:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

metricsgatherer:
  repository: reportportal/service-metrics-gatherer
  tag: 1.1.14
  name: metrics-gatherer
  loggingLevel: debug
  timeManagement:
    starttime: 22:00
    endtime: 08:00
    timezone: Europe/Minsk
  maxDaysStore: 500
  resources:
    requests:
      cpu: 8m
      memory: 128Mi
    limits:
      cpu: 16m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  serviceAccountName: ""

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: rabbitmq.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password:

postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password:

elasticsearch:
  installdep:
    enable: false
  endpoint: http://elasticsearch-master:9200

minio:
  secretName: ""
  enabled: true
  installdep:
    enable: false
  endpoint: http://minio.default.svc.cluster.local:9000
  endpointshort: minio.default.svc.cluster.local:9000
  region:
  accesskey: accesskey
  secretkey: secretkey
  bucketPrefix:
  defaultBucketName:
  integrationSaltPath:

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# tolerations for all components, if any (requires Kubernetes >= 1.6)
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute"

# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
    create: true
    name: reportportal
    # For AWS IAM role association use the following annotations
    ## See: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
    annotations:

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"
```
