### ISSUE TITLE
issues with sql scripts used for migration.

### ISSUE THREAD

**Issue by Aman-singh-wq** [reportportal/kubernetes#220]
error: Dirty database version 13. Fix and force version.

**Comment by Cyberglamdring** [comment]
Hello,

There are 2 options:

### **With data loss** 
a. Recreate `reportportal` database:
```SQL
DROP DATABASE reportportal;
CREATE DATABASE reportportal;
```
b. Install RP.

### **Without data loss**

Source [Migration down](https://github.com/reportportal/migrations)
a. Create `docker-compose.yaml`
```YAML
version: '2'
services:
  migrations:
    image: reportportal/migrations:5.6.0
    environment:
      POSTGRES_USER: <DATABASE_USER>
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: <DATABASE_PASSWORD>
      POSTGRES_SERVER: <DATABASE_URL>
      POSTGRES_DB: reportportal
    restart: on-failure`
```
b. Your database status is `13`, actual is `50` (every up script from [./migration/](https://github.com/reportportal/migrations/tree/develop/migrations)). Let's roll back to version `12` (50-12=38):
```BASH
docker-compose run --rm migrations down 38
```

c. Check migrations version:
```SQL
select * from public.schema_migrations;
```

d. Finally install RP.
