### ISSUE TITLE
Readiness Probes Failed.

### ISSUE THREAD

**Issue by manojguptavonage** [reportportal/kubernetes#285]
API and UAT pods are having issues because readiness probes are failing. I am following all the steps as mentioned in the ReadMe but I am facing the same issue always.

I am running it in minikube with docker.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/105852729/212200681-d1e7ca21-5e8a-45f0-8ce5-4203beb28934.png">

**Details:**

API Pod:

```kubectl describe pod report-reportportal-api-67fdb8577f-g5m2w
Name:             report-reportportal-api-67fdb8577f-g5m2w
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Thu, 12 Jan 2023 22:58:38 +0000
Labels:           component=report-reportportal-api
                  pod-template-hash=67fdb8577f
Annotations:      <none>
Status:           Running
IP:               172.17.0.7
IPs:
  IP:           172.17.0.7
Controlled By:  ReplicaSet/report-reportportal-api-67fdb8577f
Containers:
  api:
    Container ID:   docker://30e62fd182dbdc70f87af3003ec870e51a18cc09f5541c65323d8c8594ffeb7f
    Image:          reportportal/service-api:5.7.2
    Image ID:       docker-pullable://reportportal/service-api@sha256:9df41f8fb320092adba85922221b18280247797ab1aad4de4ecdb22fa35833a9
    Port:           8585/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 12 Jan 2023 22:58:39 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:      500m
      memory:   1Gi
    Readiness:  http-get http://:8585/health delay=90s timeout=90s period=90s #success=1 #failure=90
    Environment:
      LOGGING_LEVEL_ORG_HIBERNATE_SQL:          info
      RP_REQUESTLOGGING:                        false
      RP_AMQP_QUEUES:                           10
      RP_AMQP_QUEUESPERPOD:                     10
      JAVA_OPTS:                                -Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:MinRAMPercentage=60.0 -XX:InitiatingHeapOccupancyPercent=70 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      RP_AMQP_HOST:                             rabbitmq-local.default.svc.cluster.local
      RP_AMQP_PORT:                             5672
      RP_AMQP_ANALYZER-VHOST:                   analyzer
      RP_AMQP_USER:                             rabbitmq
      RP_AMQP_PASS:                             <set to the key 'rabbitmq-password' in secret 'rabbitmq-local'>  Optional: false
      RP_AMQP_APIPORT:                          15672
      RP_AMQP_APIUSER:                          rabbitmq
      RP_AMQP_APIPASS:                          <set to the key 'rabbitmq-password' in secret 'rabbitmq-local'>  Optional: false
      RP_DB_HOST:                               postgres-postgresql.default.svc.cluster.local
      RP_DB_PORT:                               5432
      RP_DB_NAME:                               reportportal
      RP_DB_USER:                               rpuser
      RP_DB_PASS:                               <set to the key 'postgresql-password' in secret 'postgres-postgresql'>  Optional: false
      RP_BINARYSTORE_TYPE:                      minio
      RP_BINARYSTORE_MINIO_ENDPOINT:            http://minio-local.default.svc.cluster.local:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY:           <set to the key 'access-key' in secret 'minio-local'>  Optional: false
      RP_BINARYSTORE_MINIO_SECRETKEY:           <set to the key 'secret-key' in secret 'minio-local'>  Optional: false
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED:  false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8zwp4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-8zwp4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  11m                  default-scheduler  Successfully assigned default/report-reportportal-api-67fdb8577f-g5m2w to minikube
  Normal   Pulled     11m                  kubelet            Container image "reportportal/service-api:5.7.2" already present on machine
  Normal   Created    11m                  kubelet            Created container api
  Normal   Started    11m                  kubelet            Started container api
  Warning  Unhealthy  88s (x6 over 8m58s)  kubelet            Readiness probe failed: Get "http://172.17.0.7:8585/health": dial tcp 172.17.0.7:8585: connect: connection refused```


UAT Pod:


```kubectl describe pod report-reportportal-uat-597c98f8d8-xh7p8
Name:             report-reportportal-uat-597c98f8d8-xh7p8
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Thu, 12 Jan 2023 22:58:38 +0000
Labels:           component=report-reportportal-uat
                  pod-template-hash=597c98f8d8
Annotations:      <none>
Status:           Running
IP:               172.17.0.16
IPs:
  IP:           172.17.0.16
Controlled By:  ReplicaSet/report-reportportal-uat-597c98f8d8
Containers:
  uat:
    Container ID:   docker://d98f6b6c86e3787d3d64e04320b2ee33f2a4b9fe204d2d4e1a1ecd82d729668a
    Image:          reportportal/service-authorization:5.7.0
    Image ID:       docker-pullable://reportportal/service-authorization@sha256:9e73114dbd151466624fe5d023f926fca5fbcad4a893119ce7b47d86d258c295
    Port:           9999/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 12 Jan 2023 23:10:05 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 12 Jan 2023 23:03:42 +0000
      Finished:     Thu, 12 Jan 2023 23:09:54 +0000
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     500m
      memory:  2Gi
    Requests:
      cpu:      100m
      memory:   512Mi
    Readiness:  http-get http://:9999/health delay=100s timeout=3s period=10s #success=1 #failure=5
    Environment:
      JAVA_OPTS:                       -Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0
      RP_SESSION_LIVE:                 86400
      RP_DB_HOST:                      postgres-postgresql.default.svc.cluster.local
      RP_DB_PORT:                      5432
      RP_DB_NAME:                      reportportal
      RP_DB_USER:                      rpuser
      RP_DB_PASS:                      <set to the key 'postgresql-password' in secret 'postgres-postgresql'>  Optional: false
      RP_BINARYSTORE_TYPE:             minio
      RP_BINARYSTORE_MINIO_ENDPOINT:   http://minio-local.default.svc.cluster.local:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY:  <set to the key 'access-key' in secret 'minio-local'>  Optional: false
      RP_BINARYSTORE_MINIO_SECRETKEY:  <set to the key 'secret-key' in secret 'minio-local'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2wj6s (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-2wj6s:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  12m                   default-scheduler  Successfully assigned default/report-reportportal-uat-597c98f8d8-xh7p8 to minikube
  Normal   Pulled     7m43s (x2 over 12m)   kubelet            Container image "reportportal/service-authorization:5.7.0" already present on machine
  Normal   Created    7m43s (x2 over 12m)   kubelet            Created container uat
  Normal   Started    7m42s (x2 over 12m)   kubelet            Started container uat
  Warning  Unhealthy  2m36s (x41 over 10m)  kubelet            Readiness probe failed: Get "http://172.17.0.16:9999/health": dial tcp 172.17.0.16:9999: connect: connection refused```


Can someone please share a reference to working helm charts (YAML configs) and deployment steps? I have spent multiple hours on this issue but it is not yet resolved.

Thanks

**Comment by manojguptavonage** [comment]
I am following below steps:

1/ minikube start --kubernetes-version=v1.21.0
A/helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update
B/ helm install nginx-ingress ingress-nginx/ingress-nginx --version 3.36.0

2/ minikube addons enable ingress
	
3/ helm install elasticsearch ./reportportal/charts/elasticsearch-7.10.2.tgz -f ./reportportal/elasticsearch/single-node-values.yaml

4/ helm install rabbitmq-local --set auth.username=rabbitmq,auth.password=rabbitmq,replicaCount=1 ./reportportal/charts/rabbitmq-7.5.6.tgz
A/ kubectl exec -it rabbitmq-local-0 -- rabbitmqctl set_vm_memory_high_watermark 0.8

5/ helm install postgres --set postgresqlUsername=rpuser,postgresqlPassword=rppass,postgresqlDatabase=reportportal,postgresqlPostgresPassword=password -f ./reportportal/postgresql/values.yaml ./reportportal/charts/postgresql-10.9.4.tgz
 
6/ helm install minio-local --set accessKey.password=minio,secretKey.password=minio123,persistence.size=40Gi ./reportportal/charts/minio-7.1.9.tgz

7/ Changes to values.yaml (check details below)

8/ helm package ./<folderName>/

9/ helm install report --set postgresql.SecretName=postgres-postgresql,rabbitmq.SecretName=rabbitmq-local,minio.secretName=minio-local ./reportportal-5.7.2.tgz



Values.YAML (only changed file in the folder):
```
## String to partially override reportportal.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override reportportal.fullname template
##
# fullnameOverride:

serviceindex:
  name: index
  repository: reportportal/service-index
  tag: 5.0.11
  pullPolicy: Always
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  podAnnotations: {}
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  service:
    portName: ""

uat:
  repository: reportportal/service-authorization
  name: uat
  tag: 5.7.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  podAnnotations: {}
  ## jvmArgs
  ## If you need to use a custom java keystore you can use it through jvmArgs
  ## eg. : -Djavax.net.ssl.trustStore=/etc/secret-volume/custom-pki.jks
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  ## Provide a secret containing sensitives data
  ## eg. : provide a custom java keystore used in jvmArgs
  ##
  ## keytool -genkeypair -storetype jks -alias todelete -keypass changeit -storepass changeit -keystore custom-pki.jks -dname "CN=Developer, OU=Department, O=Company, L=City, ST=State, C=CA"
  ## keytool -delete -alias todelete -storepass changeit -keystore custom-pki.jks
  ## keytool -list -keystore custom-pki.jks -storepass changeit
  ##
  ## Generate base64 data and paste it in your values.yaml :
  ## cat custom-pki.jks | base64 -w
  secret:
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
    data: {}
    #  custom-pki.jks: <base64-data>
  service:
    portName: ""

serviceui:
  repository: reportportal/service-ui
  tag: 5.7.2
  name: ui
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

serviceapi:
  repository: reportportal/service-api
  tag: 5.7.2
  name: api
  pullPolicy: Always
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 20
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  jvmArgs: "-Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -XX:MinRAMPercentage=60.0 -XX:InitiatingHeapOccupancyPercent=70 -XX:MaxRAMPercentage=90.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
  ## Number of queues
  ## Where "totalNumber" is the total number of queues
  ## Сalculation formula: perPodNumber = totalNumber / serviceapi.replicaCount
  queues:
    totalNumber:
    perPodNumber:
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  podAnnotations: {}
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

servicejobs:
  repository: reportportal/service-jobs
  tag: 5.7.2
  name: jobs
  pullPolicy: Always
  coreJobs:
    cleanAttachmentCron: 0 0 */24 * * *
    cleanLogCron: 0 0 */24 * * *
    cleanLaunchCron: 0 0 */24 * * *
    cleanStorageCron: 0 0 */24 * * *
    storageProjectCron: 0 */5 * * * *
  chunksize: 1000
  resources:
    requests:
      cpu: 100m
      memory: 248Mi
    limits:
      cpu: 100m
      memory: 372Mi
  jvmArgs: ""
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  podAnnotations: {}
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

migrations:
  repository: reportportal/migrations
  tag: 5.7.0
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  securityContext: {}
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  metadataAnnotations:
    enabled: true
    hooks:
      "helm.sh/hook": "pre-install,pre-upgrade"
      "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"

serviceanalyzer:
  repository: reportportal/service-auto-analyzer
  tag: 5.7.2
  name: analyzer
  pullPolicy: Always
  uwsgiWorkers: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 100m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  ##
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

serviceanalyzertrain:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  podAnnotations: {}
  securityContext: {}
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

metricsgatherer:
  repository: reportportal/service-metrics-gatherer
  tag: 1.1.20
  name: metrics-gatherer
  loggingLevel: debug
  timeManagement:
    starttime: 22:00
    endtime: 08:00
    timezone: Europe/Minsk
  maxDaysStore: 500
  resources:
    requests:
      cpu: 8m
      memory: 128Mi
    limits:
      cpu: 16m
      memory: 256Mi
  podAnnotations: {}
  securityContext: {}
  ## External environment variables
  ##
  extraEnvs: []
    # - name: EXTRA_ENV
    #   value: "TRUE"
    # - name: EXTRA_ENV_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: "additional-credentials"
    #       key: username
  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  #  disktype: ssd
  serviceAccountName: ""
  service:
    portName: ""

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: rabbitmq-local.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq
    password: rabbitmq
  ## Virtual hosts provide logical grouping and separation of resources.
  ## ref: https://www.rabbitmq.com/vhosts.html
  vhost: analyzer

postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    address: postgres-postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    ## Whether or not to use SSL
    ssl: disable
    # ssl: disable / require
    password: rppass
    ## Number of database connections
    connections:

elasticsearch:
  secretName: ""
  installdep:
    enable: false
  endpoint: http://elasticsearch-master.default.svc.cluster.local:9200
  user: elastic
  password:

minio:
  secretName: ""
  enabled: true
  installdep:
    enable: false
  endpoint: http://minio-local.default.svc.cluster.local:9000
  endpointshort: minio-local-minio.default.svc.cluster.local:9000
  region: ""
  accesskey: minio
  secretkey: minio123
  accesskeyName: "access-key"
  secretkeyName: "secret-key"
  bucketPrefix: ""
  defaultBucketName: ""
  integrationSaltPath: ""

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - 10.102.170.96
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
  tls: []
  # - hosts:
  #   - reportportal.k8.com
  #   secretName: reportportal.k8.com-tls

# tolerations for all components, if any (requires Kubernetes >= 1.6)
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute"

# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
    create: true
    name: reportportal
    # For AWS IAM role association use the following annotations
    ## See: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
    annotations: {}

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"

# Extra init containers to e.g. wait for minio
extraInitContainers: {}
  # - name: "wait-for-minio"
  #   image: "busybox"
  #   imagePullPolicy: "IfNotPresent"
  #   command:
  #     - sh
  #     - "-c"
  #     - "for i in `seq 1 300`; do sleep 1; if wget http://<minio-release-name>-minio.default.svc.cluster.local:9000/minio/health/live -q -O /dev/null ; then exit 0; fi; done; exit 1"
```

I have even tried to increase the 'initialDelaySeconds' in readinessProbe but it did not help.
