### ISSUE TITLE
Request for Traefik Ingress controller support for reportportal-gateway-ingress

### ISSUE THREAD

**Issue by assiakhateeb** [reportportal/kubernetes#297]
I am currently using Traefik Ingress controller in my Kubernetes cluster and need to set the ingressClassName to "traefik" in my reportportal ingress configuration. However, Traefik Ingress controller is not mentioned in the documentation for this feature, which only lists support for nginx.

Can anyone add support for it? It would be really helpful for my use case and for others who are also using Traefik Ingress controller.

I tried this IngressRoute but it didn't work, got error:
```
main.app.cf402c.js:350 
 POST http://xxx/uat/sso/oauth/token 403 (Forbidden)
```

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: reportportal-gateway-ingress-traefik
  namespace: report-portal
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`reportportal.example.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: index
      services:
        - name: reportportal-index
          kind: Service
          port: 8080
    - match: Host(`reportportal.example.com`) && PathPrefix(`/ui`)
      kind: Rule
      middlewares:
        - name: ui      
      services:
        - name: reportportal-ui
          kind: Service
          port: 8080
    - match: Host(`reportportal.example.com`) && PathPrefix(`/uat`)
      kind: Rule
      middlewares:
        - name: uat      
      services:
        - name: reportportal-uat
          kind: Service
          port: 9999
    - match: Host(`reportportal.example.com`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: api      
      services:
        - name: reportportal-api
          kind: Service
          port: 8585       
    - match: Host(`reportportal.example.com`) && PathPrefix(`/jobs`)
      kind: Rule
      middlewares:
        - name: jobs      
      services:
        - name: reportportal-jobs
          kind: Service
          port: 8686              
---
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: index
  namespace: report-portal
spec:
  redirectRegex:
    regex: ^/(.*)
    replacement: $1                   
---
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ui
  namespace: report-portal
spec:
  redirectRegex:
    regex: ^/ui(.*)
    replacement: $1    
---
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: uat
  namespace: report-portal
spec:
  redirectRegex:
    regex: ^/uat(.*)
    replacement: $1  
---
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api
  namespace: report-portal
spec:
  redirectRegex:
    regex: ^/api(.*)
    replacement: $1  
---
# Redirect with domain replacement
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jobs
  namespace: report-portal
spec:
  redirectRegex:
    regex: ^/jobs(.*)
    replacement: $1  
```

**Comment by abarrak** [comment]
HI @assiakhateeb,

You got it right almost, the conversion in `IngressRoute` are correct but you need to change the middlewares to use strip prefix. The following worked for me:


```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ui
  namespace: report-portal
spec:
  stripPrefix:
    prefixes:
      - /ui
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: uat
  namespace: report-portal
spec:
  stripPrefix:
    prefixes:
      - /uat
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api
  namespace: report-portal
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jobs
  namespace: report-portal
spec:
  stripPrefix:
    prefixes:
      - /jobs
```

Don't use middleware for `index`.
