### ISSUE TITLE
new helm release 5.7.4 not available

### ISSUE THREAD

**Issue by azhurbilo** [reportportal/kubernetes#303]
new helm release 5.7.4 not available https://artifacthub.io/packages/helm/reportportal/reportportal

```
dependencies:
  - name: reportportal
    repository: https://karthick-kk.github.io/helm-charts/
    version: 5.7.4
```
`Error: can't get a valid version for repositories reportportal.`
