### ISSUE TITLE
Reportportal in EKS/NGINX-ingress: http->https redirection not working

### ISSUE THREAD

**Issue by ioannis-klonatos** [reportportal/kubernetes#304]
Hello team,

We have setup using helm the following version of reportportal in our EKS cluster (info copied from login screen):

`Current version: API Service: 5.7.2; Jobs Service: 5.7.2; Authorization Service: 5.7.0; Service UI: 5.7.2;`

We can login to reportportal and do analytics, however we cannot seem to be able to get the HTTP->HTTPS redirection working with the nginx ingress controller.

In particular, while http access works well, if we force http->https redirection in ingress, we get `Too many redirects` error. Here is a copy of our ingress options:

```
  ingress:
    enable: true
    hosts:
      - <host>
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: http
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 128m
      nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/server-snipper: |
        large_client_header_buffers 4 100k;
     nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
```

Any advice is more than welcome. Is there official documentation somewhere as to how this can be setup? 

Many thanks!
