### ISSUE TITLE
report port page is not loading

### ISSUE THREAD

**Issue by nbonagi** [reportportal/kubernetes#309]
Hi Team,

I have deployed all the application related to report portal in kubernetes cluster. All the srvices are up and running. but when I am accesing the ui page ,the page still loading now page is displying. When i check the logs from devtools it is shwoing like below

undefined or null to object
    at Function.keys (<anonymous>)
    at main.app.9c19d7.js:6:90252
    at c (main.app.9c19d7.js:12:41694)
    at Generator._invoke (main.app.9c19d7.js:12:41482)
    at S.forEach.e.<computed> [as next] (main.app.9c19d7.js:12:42117)
    at N (main.app.9c19d7.js:26:844227)
    at y (main.app.9c19d7.js:26:845066)
    at main.app.9c19d7.js:26:845721
    at i (main.app.9c19d7.js:26:906246)
    at c (main.app.9c19d7.js:26:906396)
(anonymous) @ main.app.9c19d7.j

please help.

**Comment by alec-afs** [comment]
I was having the same problem but found this issue:
https://github.com/reportportal/kubernetes/issues/288

Which was closed by this issue:
https://github.com/reportportal/kubernetes/issues/297

TL:DR - I had to adjust my ingress controller so different path requests went to the correct container/pod:

```
    - host: reportportal.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reportportal-index
                port:
                  number: 8080
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: reportportal-ui
                port:
                  number: 8080
          - path: /uat
            pathType: Prefix
            backend:
              service:
                name: reportportal-uat
                port:
                  number: 9999
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: reportportal-api
                port:
                  number: 8585
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: reportportal-jobs
                port:
                  number: 8686
```

This resolved my issue.
Hope this helps!
