### ISSUE TITLE
 Support Request: Kubernetes Version v1.25+ Support Needed

### ISSUE THREAD

**Issue by assiakhateeb** [reportportal/kubernetes#318]
**Issue Description:**
The current version of ReportPortal includes the Elasticsearch chart (elasticsearch-7.10.2), which utilizes a deprecated API. This API deprecation has been acknowledged in Kubernetes version 1.25 and later.

Chart YAML: [Chart.yaml](https://github.com/reportportal/kubernetes/blob/develop/reportportal/Chart.yaml)
```
------------------------------------------------------------------------------------------
>>> Deprecated APIs removed in 1.25 <<<
------------------------------------------------------------------------------------------
KIND                  NAMESPACE      NAME                       API_VERSION      REPLACE_WITH (SINCE)
PodDisruptionBudget   reportportal   elasticsearch-master-pdb   policy/v1beta1   policy/v1 (1.21.0)
```
The current requirement for ReportPortal supports Kubernetes versions 1.19 to 1.24. Refer to [this link](https://github.com/reportportal/kubernetes#requirements).

Support is needed to make ReportPortal compatible with Kubernetes version 1.25 and newer.

**Comment by ramir-savvy** [comment]
We had the same issue. We disabled `PodDistributionBudget`, which is the resource that uses this deprecated API, by adding `maxUnavailable: 0` to the elasticsearch section in the reportportal values file.

**Comment by hlebkanonik** [comment]
Hello! 

The ReportPortal supports Kubernetes version 1.25, but ElasticSearch version 7.10 does not. We are currently preparing a migration ReportPortal from ElasticSearch to OpenSearch.


To deploy Elasticsearch to Kubernetes version 1.25, please follow the options below:
1. If `elasticserach.installdep.enable=true` add to the [values.yaml](https://github.com/reportportal/kubernetes/blob/master/reportportal/values.yaml#L425) to elasticsearch [maxUnavailable: false](https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L215C1-L216C1)

```yaml
elasticsearch:
  maxUnavailable: false
  secretName: ""
  installdep:
    enable: true
  ## Double entry moves test logs from PostgreSQL to Elastic-type engines
  ## Ref: https://reportportal.io/blog/double-entry-in-5.7.2
  ##
  ## ElasticSearch Performance tuning
  ## Ref: https://reportportal.io/docs/installation-steps/OptimalPerformanceHardwareSetup/#7-elasticsearch-performance-tuning
  ##
  doubleEntry:
    enable: true
  endpoint: http://elasticsearch-master.default.svc.cluster.local:9200
  user: elastic
  password:
```

2. If you are using a separate ElasticSearch Helm Chart, please upgrade the Chart with the parameter `--set maxUnavailable=0`
