### ISSUE TITLE
UAT failed to start after migration to 23.2

### ISSUE THREAD

**Issue by Idosegal** [reportportal/kubernetes#343]
Hi,

I tried to migrate our report portal from 23.1 to 23.2 and I'm facing an issue with uat.
```
2023-12-25 08:26:52.049 ERROR 1 --- [main] c.e.t.r.f.dist           ributed.s3.S3DataStore     : Unable to find file 'keystore/secret-integration-salt'

java.lang.IllegalArgumentException: Empty key
```

This is my minio configurations in values.yaml:

```
storage:
  type: minio
  installdep:
    enable: false
  secretName: "storage-password"
  accesskeyName: "access-key"
  secretkeyName: "secret-key"
  accesskey: "minio"
  secretkey: "secret"
  endpoint: http://minio.report-portal.svc.cluster.local:9000
  endpointshort: minio.report-portal.svc.cluster.local:9000
  region: "eu-central-1"
  bucket:
    type: single
    bucketDefaultName: ""
    buckerPrefix: ""
```

Can someone can assist with this? I've followed the migration guide, but nothing helped.
