### ISSUE TITLE
[Feature] Add Annotations to the Service Templates

### ISSUE THREAD

**Issue by tomikonio** [reportportal/kubernetes#359]
The service templates do not support adding arbitrary annotations:
```
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceapi.name | default "api" }}
    infoEndpoint: "/api/info"
    healthEndpoint: "/api/health"
```

We should be able to add them, they are needed for example to specify health checks for AWS LB controller:
```
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.serviceapi.service.annotations | indent 4 }}
    service: {{ $.Values.serviceapi.name | default "api" }}
    infoEndpoint: "/api/info"
    healthEndpoint: "/api/health"
```

I can open a PR if it is possible.

**Comment by hlebkanonik** [comment]
Hi @tomikonio,

Please create a PR to develop branch, but please change `indent` to `nindent` with the correct indentations level:

```yaml
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-api
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceapi.name | default "api" }}
    infoEndpoint: "/api/info"
    healthEndpoint: "/api/health"
    {{ toYaml .Values.serviceapi.service.annotations | nindent 4 }}
spec:
<...>
```
