### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by Uritassa** [reportportal/kubernetes#364]
Hi
I need some help with an issue I'm facing after deploying RP using the Helm chart here.
I managed to deploy RP without any errors, but when I try to access the web UI using port-forward, it gets stuck on "Loading". I've double-checked all the deployment steps and everything seems fine, but I still can't access the web UI as expected.

$helm install reportportal --set uat.superadminInitPasswd.password="MyPassword" reportportal/reportportal
all pods running without any error
```
$ kubectl get pods
opensearch-cluster-master-0                       1/1     Running     0          36m
reportportal-analyzer-0                            1/1     Running     0          36m
reportportal-analyzer-train-0                      1/1     Running     0          36m
reportportal-api-5677c86c48-z4p9g                 1/1     Running     0          36m
reportportal-index-65c8896df4-4kq9v              1/1     Running     0          36m
reportportal-jobs-67d85f5dcc-rhqcg              1/1     Running     0          36m
reportportal-metrics-gatherer-f8b9b57f4          1/1     Running     0          36m
reportportal-migrations-n66fr                   0/1     Completed   0          36m
reportportal-minio-87dd8c5d6-5stsr            1/1     Running     0          36m
reportportal-postgresql-0                        1/1     Running     0          36m
reportportal-rabbitmq-0                         1/1     Running     0          36m
reportportal-uat-dc4fb87ff-fzsf8               1/1     Running     0          36m
reportportal-ui-84497f7b87-mmmvn                1/1     Running     0          36m
``` 

```
$ kubectl get pvc
NAME                                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-reportportal-postgresql-0                          Bound    pvc-52519b02-3d30-4983-9df7-82588966405f   8Gi        RWO          gp2            
data-reportportal-rabbitmq-0                            Bound    pvc-c17b6adf-7504-4a32-aade-cbdd7311e4a1   8Gi            RWO       gp2            
opensearch-cluster-master-opensearch-cluster-master-0   Bound    pvc-1dbb9a08-7eaf-4f10-936f-75115a29e6ca  8Gi   RWO    gp2          
reportportal-minio                                      Bound    pvc-ae637829-d689-4e75-ab3e-0dfca3641e17   8Gi                      RWO      gp2                

``` 
```
ui logs:
127.0.0.1 - - [19/Feb/2024:01:16:50 +0000] "GET /composite/info HTTP/1.1" 304 0 "http://localhost:37205/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
127.0.0.1 - ui [19/Feb/2024:01:16:51 +0000] "GET /api/v1/user HTTP/1.1" 304 0 "http://localhost:37205/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"
10.0.93.144 - - [19/Feb/2024:01:16:56 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.26+"
10.0.93.144 - - [19/Feb/2024:01:17:06 +0000] "GET /ui/health HTTP/1.1" 200 1818 "-" "kube-probe/1.26+"
```

**Comment by raikbitters** [comment]
@Uritassa  hello. Please confirm which version of the Helm chart you have installed. Also, could you show the response body for GET /composite/info ?

**Comment by Uritassa** [comment]
> @Uritassa hello. Please confirm which version of the Helm chart you have installed. Also, could you show the response body for GET /composite/info ?
> 
> What did you do for "using port-forward" ? You may have the wrong configuration.

Helm chart v3.13.1
kubectl port-forward reportportal-ui-84497f7b87-krm5r 3000:8080 /
kubectl port-forward svc/reportportal-ui 3000:8080
```
$ curl http://localhost:3000
<!doctype html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><title>Report Portal</title><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="icon" href="favicon.ico" integrity="sha256-aSLjBCQALdnKIlbJ063QGA/8ElrgLRolXWXBRoDyOt4= sha384-Rut7kVmXU0vQgi+BSBPu7ERfVbfylYcbg1w5/+ry42toYCDHwi2pqmQiM5QQanAm" crossorigin="anonymous"><script defer="defer" src="polyfills.app.34483d47.js" integrity="sha256-SswcXJkeow42tR6QILtZzEtUYVGYPXrSwNe8RF0pyVQ= sha384-s7eUXEzN8HiT7+Frz5uKJeogYHNo8CpPqYAuEG9OhVRHVyjXs+PdStTpWEKT8NUZ" crossorigin="anonymous"></script><script defer="defer" src="styles.app.608a049b.js" integrity="sha256-AofOqZL39mcDyCWJJoJHVLVnPa6+hAcoR3tY9cMHAtA= sha384-JagMpHTfndhxOUHGCW/AJzlKzBFfqEB+saHIVdqifosB1sftLx+Q18516kb2ibVk" crossorigin="anonymous"></script><script defer="defer" src="main.app.ffa3d937.js" integrity="sha256-I+IVc5FVn3jHy4XnC5xP8H1Q9UIbEvEARUSCZu0I4rQ= sha384-ZVJgUNyXODJbn2OcqflEt23fjj6oNXhVOa5La58zfSoXyNvn3/akFaiqQWA/yCPw" crossorigin="anonymous"></script><link href="styles.7e311c.css" rel="stylesheet" integrity="sha256-+rFVnWkPai4n11YDFVq1TiLWndacCXYAluxO7pSXnjk= sha384-TuvX/kCl+u5qhA/9w3sJmQLj0v59k7rHw4JtJfZssBB8qvD3VsYvMBP1T3BJIKq/" crossorigin="anonymous"><link href="main.45bb3b.css" rel="stylesheet" integrity="sha256-qUpt/s5eu7MaRfsjY1nkWrLmKCJ9J2pZHND3ZZ7Lg1w= sha384-JBLMQ5s+8AA1IcPr8w8e12QFP1NAvbS+dAMVEhOGYzZkG3djcmNQDXaW8uxA2IFa" crossorigin="anonymous"></head><body><div id="app" style="width: 100%; height: 100%;"></div><div id="popover-root"></div><div id="modal-root"></div><div id="tooltip-root"></div><div id="notification-root"></div><div id="screen-lock-root"></div></body></html>
``` 
![rp http](https://github.com/reportportal/kubernetes/assets/134620268/541b0c50-dc01-4add-b595-010409601de0)

**Comment by raikbitters** [comment]
Hello @Uritassa. Please use the latest Report Portal helm chart 24.2 https://github.com/reportportal/kubernetes/releases/tag/reportportal-23.2.0.

Also, provide response body from GET /composite/info. 

If you can do it, you have wrong routes configuration. Index service must be rout service.

@hlebkanonik could you check this issue?

**Comment by Uritassa** [comment]
> Hello @Uritassa. Please use the latest Report Portal helm chart 24.2 https://github.com/reportportal/kubernetes/releases/tag/reportportal-23.2.0.
> 
> Also, provide response body from GET /composite/info.
> 
> If you can do it, you have wrong routes configuration. Index service must be rout service.
> 
> @hlebkanonik could you check this issue?

sorry for the misunderstanding I'm using the latest updated helm chart version

**Comment by fkapoko** [comment]
I am having the same issue as @Uritassa, using the latest version 24.2, everything deployed successfully but the pages is shows a "Loading ..." message. I am running in an openshift cluster and trying to access via an openshift route created to the ui service

<!doctype html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><title>Report Portal</title><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="icon" href="favicon.ico" 
REDACTED
crossorigin="anonymous"></head><body><div id="app" style="width: 100%; height: 100%;"></div><div id="popover-root"></div><div id="modal-root"></div><div id="tooltip-root"></div><div id="notification-root"></div><div id="screen-lock-root"></div></body></html>%

**Comment by hlebkanonik** [comment]
Hi @fkapoko, @Uritassa,

Could you provide information on the CPU and memory resources allocated and available within your clusters?

**Comment by Uritassa** [comment]
> Hi @fkapoko, @Uritassa,
> 
> Could you provide information on the CPU and memory resources allocated and available within your clusters?

```
$ kubectl get pods -o wide
NAME                                             READY   STATUS      RESTARTS   AGE   IP             NODE                                         NOMINATED NODE   READINESS GATES
opensearch-cluster-master-0                      1/1     Running     0          15m   10.0.117.115   ip-10-0-102-107.us-west-1.compute.internal   <none>           <none>
reportportal-analyzer-0                          1/1     Running     0          15m   10.0.67.174    ip-10-0-87-224.us-west-1.compute.internal    <none>           <none>
reportportal-analyzer-train-0                    1/1     Running     0          15m   10.0.118.117   ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-api-7cb5b6bc44-cpvjk                1/1     Running     0          15m   10.0.127.120   ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-index-77965dd774-fpm4j              1/1     Running     0          15m   10.0.101.35    ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-jobs-95f84c8cf-l4xfr                1/1     Running     0          15m   10.0.70.141    ip-10-0-87-224.us-west-1.compute.internal    <none>           <none>
reportportal-metrics-gatherer-7f8488544b-spkc6   1/1     Running     0          15m   10.0.105.207   ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-migrations-9lx4s                    0/1     Completed   0          15m   10.0.124.21    ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-minio-75fd8f78b4-8jvns              1/1     Running     0          15m   10.0.114.20    ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-postgresql-0                        1/1     Running     0          15m   10.0.81.210    ip-10-0-87-224.us-west-1.compute.internal    <none>           <none>
reportportal-rabbitmq-0                          1/1     Running     0          15m   10.0.123.133   ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-uat-54f99b84cc-r2nhj                1/1     Running     0          15m   10.0.98.203    ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
reportportal-ui-65599b87b5-86m6d                 1/1     Running     0          15m   10.0.107.193   ip-10-0-108-80.us-west-1.compute.internal    <none>           <none>
``` 

```
$ kubectl top node
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-0-102-107.us-west-1.compute.internal   63m          3%     1656Mi          23%       
ip-10-0-108-80.us-west-1.compute.internal    113m         5%     4297Mi          60%          
ip-10-0-87-224.us-west-1.compute.internal    381m         19%    6660Mi          93% 
``` 


```
$ curl localhost:30333/composite/info
<!doctype html><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><title>Report Portal</title><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="X-UA-Compatible" content="IE=edge"><link rel="icon" href="favicon.ico" integrity="sha256-aSLjBCQALdnKIlbJ063QGA/8ElrgLRolXWXBRoDyOt4= sha384-Rut7kVmXU0vQgi+BSBPu7ERfVbfylYcbg1w5/+ry42toYCDHwi2pqmQiM5QQanAm" crossorigin="anonymous"><script defer="defer" src="polyfills.app.34483d47.js" integrity="sha256-SswcXJkeow42tR6QILtZzEtUYVGYPXrSwNe8RF0pyVQ= sha384-s7eUXEzN8HiT7+Frz5uKJeogYHNo8CpPqYAuEG9OhVRHVyjXs+PdStTpWEKT8NUZ" crossorigin="anonymous"></script><script defer="defer" src="styles.app.608a049b.js" integrity="sha256-AofOqZL39mcDyCWJJoJHVLVnPa6+hAcoR3tY9cMHAtA= sha384-JagMpHTfndhxOUHGCW/AJzlKzBFfqEB+saHIVdqifosB1sftLx+Q18516kb2ibVk" crossorigin="anonymous"></script><script defer="defer" src="main.app.ffa3d937.js" integrity="sha256-I+IVc5FVn3jHy4XnC5xP8H1Q9UIbEvEARUSCZu0I4rQ= sha384-ZVJgUNyXODJbn2OcqflEt23fjj6oNXhVOa5La58zfSoXyNvn3/akFaiqQWA/yCPw" crossorigin="anonymous"></script><link href="styles.7e311c.css" rel="stylesheet" integrity="sha256-+rFVnWkPai4n11YDFVq1TiLWndacCXYAluxO7pSXnjk= sha384-TuvX/kCl+u5qhA/9w3sJmQLj0v59k7rHw4JtJfZssBB8qvD3VsYvMBP1T3BJIKq/" crossorigin="anonymous"><link href="main.45bb3b.css" rel="stylesheet" integrity="sha256-qUpt/s5eu7MaRfsjY1nkWrLmKCJ9J2pZHND3ZZ7Lg1w= sha384-JBLMQ5s+8AA1IcPr8w8e12QFP1NAvbS+dAMVEhOGYzZkG3djcmNQDXaW8uxA2IFa" crossorigin="anonymous"></head><body><div id="app" style="width: 100%; height: 100%;"></div><div id="popover-root"></div><div id="modal-root"></div><div id="tooltip-root"></div><div id="notification-root"></div><div id="screen-lock-root"></div></body></html>
``` 
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
![image](https://github.com/reportportal/kubernetes/assets/134620268/522dabcd-b11a-4ec0-921e-acf985cf42a8)

**Comment by NikitaGavruk** [comment]
Same!

**Comment by jason-idk** [comment]
Experiencing the same issue. Is there a known cause for this behavior yet? Any temporary workaround that can be put into place?

**Comment by ShaiShalevSQream** [comment]
Same

**Comment by hlebkanonik** [comment]
`/composite/info` must return `JSON` like this https://demo.reportportal.io/composite/info. The root path must redirect all requests to the [index service](https://github.com/reportportal/kubernetes/blob/develop/reportportal/templates/ingress/gateway-ingress.yaml#L56).

Do you use OpenShift?

**Comment by ShaiShalevSQream** [comment]
For me it happens both on minikube and on gke (with enough resources)

I tried the docker-compose option just to test it and it worked. But I actually need the helm chart on my cluster.

**Comment by Uritassa** [comment]
> `/composite/info` must return `JSON` like this https://demo.reportportal.io/composite/info. The root path must redirect all requests to the [index service](https://github.com/reportportal/kubernetes/blob/develop/reportportal/templates/ingress/gateway-ingress.yaml#L56).
> 
> Do you use OpenShift?

running on EKS cluster

**Comment by varadanandyala** [comment]
Do we have any solution for this issue?
I am experiencing this issue in EKS cluster with latest helm chart?

**Comment by ShaiShalevSQream** [comment]
in gke i had this proiblem also.
manged only to make it work with setting up ingress.
then i could access the ui

``````
ingress:
  enable: true
  hosts:
    - report-portal.address.com
  path:
  class: gce
  annotations:
    gce:
      external-dns.alpha.kubernetes.io/hostname: report-portal.my-address.com
    custom: {}
  tls:
    certificates:
     - secretName: tls-cert
       hosts:
         - report-portal.address.com

``````

i use external dns and  have a tls..

**Comment by Uritassa** [comment]
> in gke i had this proiblem also. manged only to make it work with setting up ingress. then i could access the ui
> 
> ```
> ingress:
>   enable: true
>   hosts:
>     - report-portal.address.com
>   path:
>   class: gce
>   annotations:
>     gce:
>       external-dns.alpha.kubernetes.io/hostname: report-portal.my-address.com
>     custom: {}
>   tls:
>     certificates:
>      - secretName: tls-cert
>        hosts:
>          - report-portal.address.com
> ```
> 
> i use external dns and have a tls..

I tried both ingress and port-forward and I got the same "Loading..." result.

**Comment by Uritassa** [comment]
The problem was when I tried to create my own ingress without knowing that it already existed in the cluster after I deployed Reportportal. That's why creating an ingress only for the ui service or using a port-forward doesn't work.


```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-protocol: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  generation: 1
  name: reportportal-gateway-ingress
  namespace: reportportal
spec:
  tls:
    - secretName: tls-cert
      hosts:
        - reportportal.example.com
  ingressClassName: nginx
  rules:
  - host: reportportal.example.com
  - http:
      paths:
      - backend:
          service:
            name: reportportal-index
            port:
              name: headless
        path: /
        pathType: Prefix
      - backend:
          service:
            name: reportportal-ui
            port:
              name: headless
        path: /ui
        pathType: Prefix
      - backend:
          service:
            name: reportportal-uat
            port:
              name: headless
        path: /uat
        pathType: Prefix
      - backend:
          service:
            name: reportportal-api
            port:
              name: headless
        path: /api
        pathType: Prefix
```
