### ISSUE TITLE
SSO doesnt work for reportportal-24.1.0 in compare with reportportal-23.2.0

### ISSUE THREAD

**Issue by svaraksin-gd** [reportportal/kubernetes#371]
Hi team,

I have installed a new version of reportportal kubernetes (reportportal-24.1.0) in order to test it before we migrate from previous one. And SAML SSO looks like doesn't work for this new version, see info below:

# reportportal-23.2.0 SSO:
<img width="1006" alt="reportportal-sso-config" src="https://github.com/reportportal/kubernetes/assets/133391708/7ecc51d1-b240-4394-a364-a7fc7c92087d">
<img width="1024" alt="reportportal-sso" src="https://github.com/reportportal/kubernetes/assets/133391708/a59a6325-f39e-4623-a324-86e9d0f45cd4">

```
serviceindex:
  repository: reportportal/service-index
  tag: 5.10.1
serviceui:
  repository: reportportal/service-ui
  tag: 5.10.0
serviceapi:
  repository: reportportal/service-api
  tag: 5.10.1
uat:
  repository: reportportal/service-authorization
  tag: 5.10.0
servicejobs:
  repository: reportportal/service-jobs
  tag: 5.10.0
serviceanalyzer:
  repository: reportportal/service-auto-analyzer
  tag: 5.10.0
metricsgatherer:
  repository: reportportal/service-metrics-gatherer
  tag: 5.10.0
migrations:
  repository: reportportal/migrations
  tag: 5.10.1
```

# reportportal-24.1.0 SSO:
<img width="649" alt="reportportal-new-sso-config" src="https://github.com/reportportal/kubernetes/assets/133391708/3b9c0ae8-02a0-4dc3-8b3c-3bc4d839f8db">
<img width="1119" alt="reportportal-new-sso" src="https://github.com/reportportal/kubernetes/assets/133391708/a98649fe-c897-4752-879c-6f2aac6b9f68">

```
serviceindex:
  name: index
  image:
    repository: reportportal/service-index
    tag: 5.11.0
serviceui:
  name: ui
  image:
    repository: reportportal/service-ui
    tag: 5.11.0
serviceapi:
  name: api
  image:
    repository: reportportal/service-api
    tag: 5.11.0
uat:
  name: uat
  image:
    repository: reportportal/service-authorization
    tag: 5.11.0
servicejobs:
  name: jobs
  image:
    repository: reportportal/service-jobs
    tag: 5.11.0
serviceanalyzer:
  name: analyzer
  image:
    repository: reportportal/service-auto-analyzer
    tag: 5.11.0
metricsgatherer:
  name: metrics-gatherer
  image:
    repository: reportportal/service-metrics-gatherer
    tag: 5.11.0
migrations:
  image:
    repository: reportportal/migrations
    tag: 5.11.0
postgresql: 
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 11.22.0
rabbitmq:
  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 3.10.25
opensearch:
  image:
    repository: opensearchproject/opensearch
    tag: 2.11.1
```

Is there missed somtehing? Thanks in advance
