### ISSUE TITLE
None of the “sha384” hashes in the integrity attribute match the content of the subresource

### ISSUE THREAD

**Issue by meisfrancis** [reportportal/kubernetes#378]
Hi team,
I've just implemented the latest version of reportportal. But when I access the page via my host `/ui`, it throws the error `None of the “sha384” hashes in the integrity attribute match the content of the subresource` and blocks all the script and thus making the blank page.

Here is the error details
```shell
  The resource from “https://<redacted>/ui/main_app.app.0959f63e.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
    [ui](https://<redacted>/ui/)
    None of the “sha384” hashes in the integrity attribute match the content of the subresource. The computed hash is “OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb”. [ui](https://<redacted>/ui/)
  The resource from “https://<redacted>/ui/main.app.485a554b.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
    [ui](https://<redacted>/ui/)
    None of the “sha384” hashes in the integrity attribute match the content of the subresource. The computed hash is “OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb”. [ui](https://<redacted>/ui/)
  The resource from “https://<redacted>/ui/polyfills.app.cf946401.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
    [ui](https://<redacted>/ui/)
    None of the “sha384” hashes in the integrity attribute match the content of the subresource. The computed hash is “OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb”.
```
    
Here is the Helmchart values
```yaml
  fullnameOverride: reportportal
  serviceui:
    resources:
      requests:
        cpu: 500m
        memory: 1536Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  uat:
    superadminInitPasswd:
      secretName: reportportal-secrets
      passwordKeyName: uat
  serviceapi:
    replicaCount: 2
    resources:
      requests:
        cpu: '1'
        memory: 3072Mi
      limits:
        cpu: '2'
        memory: 5120Mi
  serviceanalyzer:
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 768Mi
  servicejobs:
    resources:
      requests:
        cpu: 600m
        memory: 3072Mi
      limits:
        cpu: 1000m
        memory: 5120Mi
  storage:
    secretName: "reportportal-secrets"
    endpoint: minio.minio.svc.cluster.local
    accesskeyName: access-key
    secretkeyName: secret-key
    region: "ap-southeast-1"
    bucket:
      type: single
      bucketDefaultName: <redacted>
  searchengine:
    endpoint: elasticsearch-master.reportportal.svc.cluster.local
    user: ""
    password: ""
  msgbroker:
    ssl: true
    secretName: reportportal-secrets
    apiuser: RabbitMQreportportal
    user: RabbitMQreportportal
    apiport: 15671
    port: 5671
    endpoint:
  database:
    secretName: reportportal-secrets
    user: reportportal
    endpoint: <redacted>
  ingress:
    fullName: reportportal
    labels:
      app.kubernetes.io/name: reportportal
      app.kubernetes.io/instance: reportportal
    annotations:
      nginx:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 128m
        nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
        nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
        nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 512k
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "8000"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "4000"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "4000"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
        nginx.ingress.kubernetes.io/cors-allow-headers: access-token,Accept,Content-Type,Referer,User-Agent,x-interface-id,x-interface-type
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - <redacted>
  rabbitmq:
    install: false
  postgresql:
    install: false
  minio:
    install: false
  opensearch:
    install: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn:
    
```

Tell me if you need more information.
