### ISSUE TITLE
Parsing error in the API deployment template

### ISSUE THREAD

**Issue by BMlan-kj-GH** [reportportal/kubernetes#379]
Hi team,

We are trying to add a security context in the API service this way:

```
serviceapi:
  <Other configuration values>
  securityContext:
    runAsNonRoot: true
```

But this is failing with the following error:
YAML parse error on reportportal/templates/api-deployment.yaml: error converting YAML to JSON: yaml: line 111: mapping values are not allowed in this context

Digging into the template we find this:

```
      securityContext:
{{- toYaml .Values.serviceapi.securityContext | indent 8 }}
```

and removing the hyphen before the toYaml it works.

Our question is, are we doing something wrong or is this a typo?

Thanks in advance.

Best,
Maren
