### ISSUE TITLE
[Question] 24.2 Number of Queues for Multiple API Servers

### ISSUE THREAD

**Issue by tomikonio** [reportportal/kubernetes#454]
Hi,
Upgrading to `24.2.0` from `24.1.0`.
The queue settings have changed.
From (default):
```
  ## Number of queues
  ## Where "totalNumber" is the total number of queues. Сalculation formula: perPodNumber = totalNumber / serviceapi.replicaCount
  queues:
    totalNumber: 10
    perPodNumber: 10
```
TO (default):
```
 ## @param serviceapi.amqp define the configuration for the AMQP
  amqp:
    ## @param serviceapi.amqp.queues define the number for the queues
    ##
    queues: 10
    ## @param serviceapi.amqp.prefetchCount define the prefetch count per consumer
    ## 
    prefetchCount: 10
    ## @param serviceapi.amqp.consumersCount define time to live in parking lot queue
    ## 
    parkingLotTtlDays: 7
```

Assuming we are using 2 API server replicas, what should the new configuration numbers be?
Currently, we have it set to:
```
  queues:
    totalNumber: 20
    perPodNumber: 10
```
Should we keep the new default or change to `amqp.queues=20` ?
