### ISSUE TITLE
Hanging 'Pending' backend containers deployments on EKS

### ISSUE THREAD

**Issue by amasu** [reportportal/kubernetes#458]
Hello,

I am trying to deploy reportportal on EKS, using the helm chart provided on the official repo.
The cluster cas created using eksctl in AutoMode.

When installing the chart, no errors are thrown. The pods are created but the backend containers never spin (please see screenshot below).
The ui is reachable on the browser, which let me believe the ingress configuration is fine? Please correct me if I am wrong.
My understanding from the 'migrations' container log, is that opensearch and postgres containers never start, and are not reachable by the migrations container.

I've tried restarting the migrations container but this did not help. Neither restarting postres or opensearch... 

Any help would be appreciated, thanks.

<img width="665" alt="Image" src="https://github.com/user-attachments/assets/4715e348-99eb-4046-831c-58035064ad64" />

Migration logs:

> kubectl logs rp-01-reportportal-migrations-jb8sl 
> wait-for-it.sh: waiting for opensearch-cluster-master.default.svc.cluster.local:9200 without a timeout
> wait-for-it.sh: waiting for rp-01-postgresql.default.svc.cluster.local:5432 without a timeout

**Comment by hlebkanonik** [comment]
Hi! The migration reports that it can't reach OpenSearch and Postgres. I also noticed that RabbitMQ is in a Pending state. Please check why these pods are not running.

**Comment by amasu** [comment]
> Hi! The migration reports that it can't reach OpenSearch and Postgres. I also noticed that RabbitMQ is in a Pending state. Please check why these pods are not running.

Hello, 

Thank you for your reply. 
That's exactly what I am trying to figure out: I think the opensearch and postgres containers are not starting (status is permanently pending). Same for minio and rabbitMQ containers. Forcing a restart of these containers does not solve the issue. And there are no log for these containers (it makes sense, as they never start). 
I've also tried forcing a higher resource allocation (cpu and memory) by tweaking the helm chart values.yaml, but without any change in these containers behavior. 

I have to admit I am running dry on this one :/

**Comment by hlebkanonik** [comment]
Hi! Try describing the pod and checking the events. If it's a fresh EKS cluster, the issue might be with the EBS CSI Driver. However, I heard that the driver is enabled by default in Auto Mode

**Comment by hlebkanonik** [comment]
Hi! Have you resolved the issue?

**Comment by amasu** [comment]
Hello,

Not yet unfortunately. I am exploring several potential causes at the same time in between my different tasks. 
Right now I am considering the possibility that some pods are not starting because of the lack of resources... Which is IMO less likely because I use the auto mode feature of eksctl that is supposed to automatically manage the needed resources. But I'm so desperate :D Last thing I checked is trying to force the usage of additional resources by explicitly defining the EC2 instance types in my Kubernetes config... So far without success. 

I am sorry for my late answers and thank you again for following up with this.

**Comment by hlebkanonik** [comment]
If you have any questions, feel free to reach out. We're working closely with EKS, although the Auto Mode is still planned for future testing. You can follow our progress and updates in upcoming blog posts here: https://reportportal.io/blog

**Comment by amasu** [comment]
SOLVED

The cause of the issue: Persistent volumes were not created :/ For a reason I don't know yet... I have imagined that autoMode of eksctl would automatically create persistent volumes but it seems it doesn't create them during the cluster creation.
I worked around it by creating yaml config files for the storageClass and the PV. 

A short summary of my setup before I spam you with yaml code:
- EKS cluster in Automode.
- Applied custom config for the storage class and the PV.
- Applied custom config for the ingress (using alb instead of the default nginx).
- Tweaked the helm chart configuration (values.yaml) to introduce alb annotations in the ingress config section.

**EKS config:**

1. storageClass.yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auto-ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
```
2. pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: auto-ebs-sc
  resources:
    requests:
      storage: 30Gi
```
3. ingressClass.yaml
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb
```
4. ingressClassParams.yaml
```
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
spec: 
  scheme: internet-facing
```
5. ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rp-ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - backend:
            service:
              name: rp-01-reportportal-index
              port:
                name: headless
          path: /
          pathType: Prefix
        - backend:
            service:
              name: rp-01-reportportal-ui
              port:
                name: headless
          path: /ui
          pathType: Prefix
        - backend:
            service:
              name: rp-01-reportportal-uat
              port:
                name: headless
          path: /uat
          pathType: Prefix
        - backend:
            service:
              name: rp-01-reportportal-api
              port:
                name: headless
          path: /api
          pathType: Prefix
```
 
**Helm chart tweak (values.yaml):**
```
ingress:
  enable: true
  ## @param ingress.hosts can be a list or a single string
  ##
  hosts: rp-k8s-alb-xxxxxxxx.eu-west-1.elb.amazonaws.com
  path: null
  class: alb
  annotations:
    alb:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
      alb.ingress.kubernetes.io/group.name: reportportal-alb
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=1800
      ingressClassName: alb
    
    gce: {}
    custom: {}
  tls:
    certificates: null
    certificate:
      gcpManaged: false
      privateKey: null
      certificate: null
```

I think this issue can be closed now.

I do however have 2 requests:
1. Would it be possible to include the alb annotations in a next release? That would allow choosing between two options for the ingress solution on EKS (nginx VS alb).
2. Since you are collaborating with EKS Team, would it be possible to suggest adding a default storageClass and PV claim to the AutoMode? 

I hope this helps, feel free to let me know if further info are required.
Thanks again for your work and for the support.
