### ISSUE TITLE
services. resources section improvement

### ISSUE THREAD

**Issue by AndreiPaulau** [reportportal/kubernetes#463]
Hello,

While `resources`.`requests/limits` section is a must, could you please leave resource/limits as an optional/free form for ALL services?

The idea is that hardened limits is a subject for CPU throttling at the envs with high number of CPUs

As of now:
```
resources:
  requests:
    cpu: {{ .Values.uat.resources.requests.cpu }}
    memory: {{ .Values.uat.resources.requests.memory }}
  limits:
    cpu: {{ .Values.uat.resources.limits.cpu }}
    memory: {{ .Values.uat.resources.limits.memory }}
```

To be
```
resources:
  {{- toYaml .Values.uat.resources | nindent 12 }}
```

Mind, `values.yaml` should be adopted to `resources: {}` as well

Thanks!
