### ISSUE TITLE
opensearch how to change initContainers busybox image

### ISSUE THREAD

**Issue by vadimprt** [reportportal/kubernetes#475]
hi, how i can change initContainers image to private registry like <registry>/busybox/busybox:latest

```
      initContainers:
        - args:
            - chown -R 1000:1000 /usr/share/opensearch/data
          command:
            - sh
            - '-c'
          image: busybox:latest
```

**Comment by vadimprt** [comment]
found https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch/values.yaml

added in reportportal values.yaml
```
opensearch:
# ...existing config...
  persistence:
    image: harbor.example.com/busybox/busybox
    imageTag: latest
```
